### ISSUE TITLE
Ceti account

### ISSUE THREAD

**Issue by BerengerBerthoul** [Ceti/blizzard#1]
Hi,
You seem to not be using the Ceti account. Would you be kind enought to release it so that I can use the name ? I think this is a great name!
From the outside, your account seems to be inactive. However, if you actually use, or plan to use "Ceti", of course don't take my request into account!
Cheers,
Berenger

**Comment by Ceti** [comment]
I am sorry, I am using this account mostly for my private projects and I am not willing to give it up. 
Cheers,
Ceti

**Comment by BerengerBerthoul** [comment]
Hi,
Thanks for the quick reply
All the best!
Berenger
